### ISSUE TITLE
Sync Permission runs too often

### ISSUE THREAD

**Issue by seanthomasdevlin** [Servoy/svySecurity#10]
- Sync in scope init only in developer
- Add import hook for deployments

**Comment by seanthomasdevlin** [comment]
Import hook may be untenable because of dependency cycle. Instead consider a config property which can disable the sync

**Comment by paronne** [comment]
Restoring auto-sync at every login by default.
Added user property option to disable auto sync.
set user.svy.security.auto-sync-permissions-when-deployed=false to prevent sync permissions running to often
