### ISSUE TITLE
permissions are not synced by default when deploying

### ISSUE THREAD

**Issue by tuanway** [Servoy/svySecurity#24]
I'm not sure if this is expected or not, but in the past permissions were synced automatically when deployed to a server.

Now I must create an import hook and run svySecurity.syncPermissions method in order to update the deployed server's permissions.

I was testing this while trying to deploy svySecurityConsole

**Comment by paronne** [comment]
Hi Tuan, are you using the latest version of svySecurity (1.4.0) ?
In version 1.3.0 permissions were not synced automatically indeed; reason was to avoid a sync at every user login.
In version 1.4.0 permissions are synced automatically on a deployed server; while using an import hook is still the preferred approach. Auto sync can be disabled via a user property.
See wiki : https://github.com/Servoy/svySecurity/wiki/Overview#synchronizing-permissions--auto-sync

**Comment by tuanway** [comment]
I used the latest from source.  I was forced to use an import hook, so was more or less curious if this is best practice now.  otherwise where does the autosync happen?

**Comment by seanthomasdevlin** [comment]
@tuanway since 1.4.0 it should be happening when the scope loads, unless disabled by configuration. Only then do you need an import hook. The idea is that early in development, permissions may be updated often, but in a stable product, it may be rare.

**Comment by tuanway** [comment]
I see the code for this now, however this assumes that you have the property created, if you do not then it will not work at all.

function getAutoSyncPermissionsEnabled() {
	var result = application.getUserProperty(USER_PROPERTIES.AUTO_SYNC_PERMISSIONS_WHEN_DEPLOYED);
	return result != "false" ? true : false;
}
