### ISSUE TITLE
Can I get ALL the properties from a property type?

### ISSUE THREAD

**Issue by juanetec** [Servoy/svySecurity#27]
Hi,
is there any option to get ALL the properties from a property type included the global, user and tenant??
This function scopes.svyProperties.getPropertiesByType(propertyType) get only the global?

Un Saludo

Juan Ramírez

**Comment by seanthomasdevlin** [comment]
Hi Juan,

I believe the method is overloaded, such that if you simply ignore those parameters, then they are not queried (meaning you get everything). But if you supply **null**, then it should return properties with no user/tenant.

for example:
`scopes.svyProperties.getPropertiesByType(propertyType); // get ALL properties`
vs
`scopes.svyProperties.getPropertiesByType(propertyType, null); // get global properties`
vs
`scopes.svyProperties.getPropertiesByType(propertyType, 'tenant-abc'); // get tenant properties`

Please reopen this if you find that it is not working correctly this way
