### ISSUE TITLE
Cache user permissions for quick check "logged user has permissions"

### ISSUE THREAD

**Issue by paronne** [Servoy/svySecurity#28]
Checking if logged user has a specific permission is a common check which may be asked many times.
some possible use cases:
check if user has permissions to access menu item X;
check if user has permissions to view appointments of other users in Agenda; 
check if user has permissions to edit appointments in Agenda; 

There can be many checks for "user has permission (permissionName)".
Consider caching permissions for the logged user for a quick check which doesn't have perfomance penalties.
Caching permissions could be a svySecurity configuration which may be enabled/disabled depending on preferences.

**Comment by seanthomasdevlin** [comment]
Planned 2021.6
https://support.servoy.com/browse/SVYX-183

**Comment by paronne** [comment]
Resolved with https://servoy-cloud.atlassian.net/browse/SVYX-290
