### ISSUE TITLE
Increase length of user_name feld

### ISSUE THREAD

**Issue by SteveHawes** [Servoy/svySecurity#29]
Currently the user_name field is limited to 50 characters. Increasingly, people are using their e-mail address as their username and this can often require a field length greater than 50 characters.

I suggest increasing it to 254 characters (the same as the email field)

**Comment by seanthomasdevlin** [comment]
Hi Steve, 
Thanks for the feedback. We can update the field length in the project code base, but this wouldn't have any effect on existing projects. You can do this by changing in your own DB. After you sync with DBI files in developer, you can update the column entry in the DBI file. This is in your resources, which is not really part of the svySecurity project. (Although, we do ship a resources project, it is merged with yours when you import it)

**Comment by seanthomasdevlin** [comment]
Planned
https://support.servoy.com/browse/SVYX-182

**Comment by paronne** [comment]
Released with svySecurity version 1.5.0
