### ISSUE TITLE
Null-Pointer-Exception in "updateOpenClientSessions"

### ISSUE THREAD

**Issue by philippr71** [Servoy/svySecurity#32]
From time to time we see a Null-Pointer-Exception in the Servoy-Admin-Log. This happens when there is a record in table "session" without a "session_start" value (I don't know how this could happen).

It happens in "svySecurityBatch.js" method "updateOpenClientSessions" line 91 ("session.session_duration = ...").

When such a record exists, then we have a lot of such errors in the log because this method is called every minute (batch-process that is schedule in onSolutionOpen of svySecurity) until we fix this record manually in the database.

**Comment by seanthomasdevlin** [comment]
Thanks Philip, session start should never be null, so that is strange indeed. We will investigate how that is possible and at least, put in a check for the null and handle accordingly.

Here's the proper support case, planned for 2021.06.
https://support.servoy.com/browse/SVYX-242

Best,
Sean

**Comment by paronne** [comment]
Case SVYX-242 resolved. Will be available with the next release
