### ISSUE TITLE
Error svySecurity Module

### ISSUE THREAD

**Issue by og1** [Servoy/svySecurity#37]
Hi, 

In the newest version of everything I get the following error when I try to select the tenant in the security module:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/8705637/167105710-2e7988bc-d866-431c-a0f6-5163623e4b34.png">

**Comment by seanthomasdevlin** [comment]
Hi og1,

It seems like the svySecurity scope is not loaded. Are you sure the SvySecurity module is in your build path. Sometimes I've seen this error in developer when something is not fully built. Often you can goose it by switching the active solution and switching back.

Best,
Sean

**Comment by og1** [comment]
Hi Sean,

Thanks, I goosed it into submission. Even though svySearch was included in the main application it couldn't find a reference to it. So I explicitly added it to the svySecurity Console project and that did the trick.
